services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3333:3000" # Mapping the host port 3333 to container's internal port 3000 (on your computer use localhost:3333).
